spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mealprepapp
    password:
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always